#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;
use File::Path;

#--------------------------------------------------
# actions for nethserver-odbc-update event
#--------------------------------------------------

my $event = "nethserver-unixODBC-update";

templates2events("/etc/odbc.ini",$event);
templates2events("/etc/odbcinst.ini",$event);

