#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;
use File::Path;

#--------------------------------------------------
# actions for nethserver-odbc-update event
#--------------------------------------------------

my $event = "nethserver-odbc-update";

event_actions($event, qw(
     initialize-default-databases 00
));

templates2events("/etc/odbc.ini",$event);
templates2events("/etc/odbcinst.ini",$event);

